services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8001:8001"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
