[project]
name = "todo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "bcrypt>=4.3.0",
    "click==8.2.1",
    "dnspython==2.7.0",
    "email-validator==2.2.0",
    "fastapi==0.116.1",
    "h11==0.16.0",
    "httpx>=0.28.1",
    "idna==3.10",
    "iniconfig==2.1.0",
    "jose>=1.0.0",
    "packaging==25.0",
    "passlib==1.7.4",
    "pluggy==1.6.0",
    "psycopg2==2.9.10",
    "pydantic==2.11.7",
    "pydantic-core==2.33.2",
    "pydantic-settings>=2.10.1",
    "pygments==2.19.2",
    "pyjwt==2.10.1",
    "pytest==8.4.1",
    "pytest-asyncio>=1.1.0",
    "python-dotenv==1.1.1",
    "python-jose>=3.5.0",
    "python-multipart==0.0.20",
    "pytz==2025.2",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.41",
    "starlette==0.47.1",
    "typing-extensions==4.14.1",
    "typing-inspection==0.4.1",
    "uvicorn==0.35.0",
]
